Questão 1

In [4]:
using LinearAlgebra

In [5]:
"""
Função que resolve e retorna Ax = b, quando A é uma matriz quadrada diagonal.
Entradas: Matriz A, uma matriz quadrada diagonal; Vetor B, uma matriz coluna.
Saídas: Vetor x, cujo elementos respeitam a equação Ax = b.
Complexidade: O(n)
"""
function resolve_diagonal(A, b)
    n = length(b) # Obtém o tamanho de b e armazena em n
    x = zeros(n) # Cria um vetor x de tamanho n
    for i = 1:n 
        x[i] = b[i]/A[i,i] # Para cada i, de 1 a n, faz x_1 = b_1/A_1,1
    end
    return x # Retorna o vetor x
end

resolve_diagonal

In [6]:
A = [1 0 0; 
     0 2 0; 
     0 0 -4]
b = [1, 1, 1]
x = resolve_diagonal(A, b)
A*x ≈ b

true

In [7]:
A = [7 0 0 0; 
     0 -8 0 0; 
     0 0 6 0;
     0 0 0 5]
b = [5, 14, 16, 8]
x = resolve_diagonal(A, b)
A*x ≈ b

true

In [8]:
A = [5 0; 
     0 4]
b = [0, -10]
x = resolve_diagonal(A, b)
A*x ≈ b

true

In [9]:
"""
Função que resolve e retorna Ax = b, quando A é uma matriz quadrada triangular superior.
Entradas: Matriz A, uma matriz quadrada triangular superior; Vetor B, uma matriz coluna.
Saídas: Vetor x, cujo elementos respeitam a equação Ax = b.
Complexidade: O(n^2)
"""
function resolve_triangular_superior(A, b)
    n = length(b) # Obtém o tamanho de b e armazena em n
    x = zeros(n) # Cria um vetor x de tamanho n
    for i = n:-1:1 # Faz i, que começa com valor n e diminui até 1
        x[i] = b[i] # Armazenda em x_i o valor b_i
        for j = i+1:n # Dentro do for, faz o b_i menos o somatório de A_i,j * x_j, e armazenar em x_i,
                      # Com j que começa com valor i+1 e cresce até n
            x[i] = x[i] - (A[i,j]*x[j])
        end
        x[i] = x[i]/A[i, i] # Por fim, dividir o o x_i atual por A_i,i, e armazenar em x_i
    end
    return x # Retorna o vetor x
end

resolve_triangular_superior

In [10]:
A = [1 2 3;
     0 4 5;
     0 0 6]
b = [1, 1, 1]
x = resolve_triangular_superior(A, b)
A*x ≈ b

true

In [11]:
A = [10 -2 34 5;
     0 -20 1 52;
     0 0 -5 7;
     0 0 0 3]
b = [11, 0, 10, -24]
x = resolve_triangular_superior(A, b)
A*x ≈ b

true

In [12]:
A = [-1 20;
     0 5]
b = [17, -41]
x = resolve_triangular_superior(A, b)
A*x ≈ b

true

In [13]:
"""
Função que resolve e retorna Ax = b, quando A é uma matriz quadrada triangular inferior.
Entradas: Matriz A, uma matriz quadrada triangular inferior; Vetor B, uma matriz coluna.
Saídas: Vetor x, cujo elementos respeitam a equação Ax = b.
Complexidade: O(n^2)
"""
function resolve_triangular_inferior(A, b)
    n = length(b) # Obtém o tamanho de b e armazena em n
    x = zeros(n) # Cria um vetor x de tamanho n
    for i = 1:n # Faz i, que começa com valor 1 e cresce até n
        x[i] = b[i] # Armazenda em x_i o valor b_i
        for j = 1:(i - 1)# Dentro do for, faz o b_i menos o somatório de A_i,j * x_j, e armazenar em x_i,
                         # Com j que começa com valor 1 e cresce até i - 1
            x[i] = x[i] - (A[i,j]*x[j])
        end
        x[i] = x[i]/A[i, i] # Por fim, dividir o o x_i atual por A_i,i, e armazenar em x_i
    end 
    return x # Retorna o vetor x
end

resolve_triangular_inferior

In [14]:
A = [1 0 0;
     2 3 0;
     4 5 6]
b = [1, 1, 1]
x = resolve_triangular_inferior(A, b)
A*x ≈ b

true

In [15]:
A = [11 0 0 0;
     -2 34 0 0;
     14 55 89 0;
    -5 12 19 3]
b = [41, 17, -1, 5]
x = resolve_triangular_inferior(A, b)
A*x ≈ b

true

In [16]:
A = [-24 0 ;
     1 58]
b = [7, 62]
x = resolve_triangular_inferior(A, b)
A*x ≈ b

true

In [17]:
"""
Função que recebe uma matriz A e retorna duas matrizes: L, uma matriz quadrada triangular inferior,
e U, uma matriz quadrada triangular superior. Essas, quando multiplicadas, equivalem a A (L*U = A)
Entradas: Matriz A, uma matriz quadrada;
Saídas: Uma matriz quadrada triangular inferior, L; Uma matriz quadrada triangular superior, U.
Complexidade: O(n^3)
"""
function decomposicao_LU(A)
    n, = size(A) # Obtém o número de linhas e colunas em A e armazena em n
    L = zeros(n, n) # Cria uma matriz quadrada L de tamanho nxn vazia
    U = copy(A) # Copia a matriz A em U
    v = 0 # Variável auxiliar
    for i = 1:n # Preenche a diagonal principal da matriz L com o número 1
        L[i,i] = 1
    end
    for i = 1:(n - 1) # For que seleciona o 'pivo' para realiza a eliminação de Gauss, e formular valores de L
        pivo = U[i,i] # Salva o pivo retirado da matriz A
        for j = i + 1:n # Realiza o for, com j representando as linhas abaixo da linha do pivo, até n
            v = U[j, i]/pivo # Atualiza a variável auxiliar v para zerar os elementos em A de mesma coluna do pivo
            for k = 1:n # Realiza o for, passando por todos os itens da linha para realizar a eliminação gaussiana
                U[j,k] = U[j,k] - U[i,k]*(v) # Realiza a eliminação gaussiana, zerando sempre os elementos da coluna do pivo
            end
            L[j, i] = v # Armazena o valor calculado para a eliminação gaussiana 
        end
    end
    return L, U # Retorna L, como uma matriz quadrada triangular inferior,
                # e U, como uma matriz quadrada triangular superior
end         

decomposicao_LU

In [18]:
A = [3.0 2.0 4.0; 
    1.0 1.0 2.0; 
    4.0 3.0 -2.0]
L, U = decomposicao_LU(A)
L*U ≈ A

true

In [19]:
A = [1.0 2.0 3.0; 
    4.0 -2.0 6.0; 
    1.0 4.0 5.0]
L, U = decomposicao_LU(A)
L*U ≈ A

true

In [20]:
A = [8.0 -4.0 -2.0; 
    -4.0 10.0 -2.0; 
    -2.0 -2.0 10.0]
L, U = decomposicao_LU(A)
L*U ≈ A

true

In [21]:
"""
Função que recebe uma matriz A e retorna A invertida. 
(Utiliza o método A*A^(-1) = I <-> L*U*A^(-1) = I, onde temos U*A^(-1) = y)
Entradas: Matriz A, uma matriz quadrada;
Saídas: A_inv, Uma matriz quadrada que é a inversa de A.
Complexidade: O(n^3)
"""

function inversa_LU(A)
    L, U = decomposicao_LU(A) # 'Desmonta' a matriz A em duas matrizes, 
                              # L (quadrada triangular inferior) e U (quadrada triangular superior)
    n, = size(A) # Obtém o número de linhas e colunas em A e armazena em n
    y = zeros(n, n) # Cria uma matiz y, que será intermediária, e a preenche com zeros
    A_inv = zeros(n, n) # Cria a matriz que sera retornada, a inversa de A, e preenche com zeros
    ident = zeros(n, n) # Cria uma matriz identidade, e a preenche com zeros
    for i = 1:n # For para preencher a diagonal da matriz identidade com 1's
        ident[i,i] = 1
    end
    for i = 1:n # For que completa a matriz A invertida, das colunas 1 a n
        y[:,i] = resolve_triangular_inferior(L, ident[:,i]) # Resolve o triangular inferior com a coluna i da matriz identidade,
                                                            # no molde L*y_:,i = I_:,i
        A_inv[:, i] = resolve_triangular_superior(U, y[:,i])# Resolve o triangular superior com a coluna i da matriz y,
                                                            # no molde U*A_:,i = y_:,i
    end
    return A_inv # Retorna a matriz A invertida
end           

inversa_LU (generic function with 1 method)

In [22]:
# Matriz identidade usada para os testes
ident = [1 0 0;
         0 1 0;
         0 0 1]

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [23]:
A = [3.0 2.0 4.0; 
    1.0 1.0 2.0; 
    4.0 3.0 -2.0]
A_inv = inversa_LU(A)
A*A_inv ≈ ident

true

In [24]:
A = [1.0 2.0 3.0; 
    4.0 -2.0 6.0; 
    1.0 4.0 5.0]
A_inv = inversa_LU(A)
A*A_inv ≈ ident

true

In [25]:
A = [8.0 -4.0 -2.0; 
    -4.0 10.0 -2.0; 
    -2.0 -2.0 10.0]
A_inv = inversa_LU(A)
A*A_inv ≈ ident

true

Questão 3

In [26]:
A = [1 -1/4 -1/4 0; -1/4 1 0 -1/4; -1/4 0 1 -1/4; 0 -1/4 -1/4 1]

4×4 Matrix{Float64}:
  1.0   -0.25  -0.25   0.0
 -0.25   1.0    0.0   -0.25
 -0.25   0.0    1.0   -0.25
  0.0   -0.25  -0.25   1.0

In [27]:
b = [5 50/4 15/4 45/4]

1×4 Matrix{Float64}:
 5.0  12.5  3.75  11.25

In [28]:
# A*x = b, onde A = L*U
# L*y = b, onde obtemos y para achar x
# U*x = y, obtendo x
@time begin
    L, U = decomposicao_LU(A)
    y = resolve_triangular_inferior(L, b)
    x = resolve_triangular_superior(U, y)
end

  0.027952 seconds (21.55 k allocations: 1.280 MiB, 99.85% compilation time)


4-element Vector{Float64}:
 13.125
 20.625
 11.875
 19.375

In [29]:
A = [1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
     -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
     0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 0 -1/4 1 0 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
     -1/4 0 0 0 0 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
     0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0 0;
     0 0 0 0 -1/4 0 0 0 -1/4 1 0 0 0 0 -1/4 0 0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 -1/4 0 0 0 0 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0 -1/4 0 0 -1/4 1 0 0 0 0 0 -1/4 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 0 1 -1/4 0 0 0 -1/4 0 0 0 0;
     0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0 0 -1/4 0;
     0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 0 0 0 0 -1/4;
     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 0 1 -1/4 0 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4 0;
     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1 -1/4;
     0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1/4 0 0 0 -1/4 1;]

25×25 Matrix{Float64}:
  1.0   -0.25   0.0    0.0    0.0   …   0.0    0.0    0.0    0.0    0.0
 -0.25   1.0   -0.25   0.0    0.0       0.0    0.0    0.0    0.0    0.0
  0.0   -0.25   1.0   -0.25   0.0       0.0    0.0    0.0    0.0    0.0
  0.0    0.0   -0.25   1.0   -0.25      0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0   -0.25   1.0       0.0    0.0    0.0    0.0    0.0
 -0.25   0.0    0.0    0.0    0.0   …   0.0    0.0    0.0    0.0    0.0
  0.0   -0.25   0.0    0.0    0.0       0.0    0.0    0.0    0.0    0.0
  0.0    0.0   -0.25   0.0    0.0       0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0   -0.25   0.0       0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0    0.0   -0.25      0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0    0.0    0.0   …   0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0    0.0    0.0       0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0    0.0    0.0       0.0    0.0    0.0    0.0    0.0
  0.0    0.0    0.0    0.0    0.0       0

In [30]:
b = [45/4 ; 
    20/4; 
    20/4 ; 
    20/4; 
    40/4; 
    25/4; 
    0; 
    0; 
    0; 
    20/4; 
    25/4; 
    0; 
    0; 
    0; 
    20/4; 
    25/4; 
    0; 
    0; 
    0; 
    20/4; 
    55/4; 
    30/4; 
    30/4; 
    30/4; 
    50/4]

25-element Vector{Float64}:
 11.25
  5.0
  5.0
  5.0
 10.0
  6.25
  0.0
  0.0
  0.0
  5.0
  6.25
  0.0
  0.0
  0.0
  5.0
  6.25
  0.0
  0.0
  0.0
  5.0
 13.75
  7.5
  7.5
  7.5
 12.5

In [31]:
# A*x = b, onde A = L*U
# L*y = b, onde obtemos y para achar x
# U*x = y, obtendo x
L, U = decomposicao_LU(A)
y = resolve_triangular_inferior(L, b)
x = resolve_triangular_superior(U, y)

25-element Vector{Float64}:
 22.544910929891554
 21.518050214897478
 20.87762318174459
 20.320043856439405
 19.899858605080322
 23.661593504668744
 22.64966674795377
 21.672398655641462
 20.502693638932705
 19.27939056388188
 24.45179634082966
 23.74662461660739
 22.659611053934803
 20.738941479768073
 16.715010011514508
 25.398967242042485
 25.225424323711348
 24.48047946372228
 23.078451214690272
 21.016764301255613
 26.918648303628935
 27.275625972473247
 26.958431262552672
 26.07761961401516
 24.27359597881769

In [65]:
A = [1 0 0 0 0 0 0 0;
     0 1 0 0 0 0 0 0;
     0 0 1 0 0 0 0 0;
    -1 0 0 1 0 0 0 0;
     0 0 -1 0 1 0 0 0;
     0 -1 0 -1 0 1 0 0;
     0 0 0 0 -1 0 1 0;
     0 0 0 0 0 -1 -1 1;]

8×8 Matrix{Int64}:
  1   0   0   0   0   0   0  0
  0   1   0   0   0   0   0  0
  0   0   1   0   0   0   0  0
 -1   0   0   1   0   0   0  0
  0   0  -1   0   1   0   0  0
  0  -1   0  -1   0   1   0  0
  0   0   0   0  -1   0   1  0
  0   0   0   0   0  -1  -1  1

In [66]:
b = [7000; 3500; 9000; 30000; 3000; 0; 3000; 500]

8-element Vector{Int64}:
  7000
  3500
  9000
 30000
  3000
     0
  3000
   500

In [67]:
# A*x = b, onde A = L*U
# L*y = b, onde obtemos y para achar x
# U*x = y, obtendo x
L, U = decomposicao_LU(A)
y = resolve_triangular_inferior(L, b)
x = resolve_triangular_superior(U, y)

8-element Vector{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

In [68]:
L*U ≈ A

true

In [62]:
A = [1 0 0 0 0 0 0 0 0;
     0 1 0 0 0 0 0 0 0;
     0 0 1 0 0 0 0 0 0;
    -1 0 0 1 0 0 0 0 -1;
     0 0 -1 0 1 0 0 0 1;
     0 -1 0 -1 0 1 0 0 0;
     0 0 0 0 -1 0 1 0 0;
     0 0 0 0 0 -1 -1 1 0;]

8×9 Matrix{Int64}:
  1   0   0   0   0   0   0  0   0
  0   1   0   0   0   0   0  0   0
  0   0   1   0   0   0   0  0   0
 -1   0   0   1   0   0   0  0  -1
  0   0  -1   0   1   0   0  0   1
  0  -1   0  -1   0   1   0  0   0
  0   0   0   0  -1   0   1  0   0
  0   0   0   0   0  -1  -1  1   0

In [63]:
# A*x = b, onde A = L*U
# L*y = b, onde obtemos y para achar x
# U*x = y, obtendo x
L, U = decomposicao_LU(A)
y = resolve_triangular_inferior(L, b)
x = resolve_triangular_superior(U, y)

8-element Vector{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

In [64]:
L*U ≈ A

false